name: Build And Push
on:
  push:
    tags:
      - 'v*'
jobs:
  build-amd64:
    name: Build and Push amd64
    runs-on: ubuntu-latest
    env:
      TAG: ${GITHUB_REF_NAME}
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        run: TAG=${TAG} make
      - name: push
        run: TAG=${TAG} make image-push
  manifest:
    name: Docker manifest
    runs-on: ubuntu-latest
    needs: build-amd64
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create and Push manifest
        env:
          TAG: ${GITHUB_REF_NAME}
          REPOSITORY_OWNER: ${{github.repository_owner}}
          REPOSITORY: ${{github.repository}}
        run: |
          docker manifest create ${REPOSITORY_OWNER}/${REPOSITORY}:${TAG} \
            ${REPOSITORY_OWNER}/${REPOSITORY}:${TAG}

          docker manifest push ${REPOSITORY_OWNER}/${REPOSITORY}:${GITHUB_REF_NAME}

